package ai.koog.book.app.model

import kotlinx.serialization.Serializable

/**
 * Represents a general message interface used within the system.
 * Implementations of this interface define various message types
 * and their associated content.
 *
 * @property messageType The type of the message, represented by an `LLMMessageType` enumeration value.
 */
@Serializable
sealed interface Message {
    val messageType: MessageType
}

@Serializable
sealed interface AgentMessage : Message {
    val message: String
}

@Serializable
sealed interface ServerMessage : Message

/**
 * Represents a message generated by the language model in the system.
 *
 * This specific implementation of the `Message` interface defaults to the
 * `ASSISTANT` message type (`LLMMessageType.ASSISTANT`).
 *
 * @property message The content of the message provided by the language model.
 */
@Serializable
data class LLMMessage(
    override val message: String
) : AgentMessage {
    override val messageType: MessageType = MessageType.ASSISTANT
}

/**
 * Represents a message of type `TOOL_CALL` used to encapsulate information about a tool call.
 *
 * @property message The content of the tool call message, formatted as "Tool Call: <toolName>, Args: <toolArgs>, Result: <result>".
 * @property messageType The type of the message, which is always `MessageType.TOOL_CALL`.
 */
@Serializable
@ConsistentCopyVisibility
data class LLMToolCallMessage private constructor(
    override val message: String
) : AgentMessage {
    constructor(toolName: String, toolArgs: String, result: String? = null) : this(
        "Tool Call:  $toolName, Args: $toolArgs, Result: $result"
    )

    override val messageType: MessageType = MessageType.TOOL_CALL
}

/**
 * Represents an error message in the LLM system.
 */
@Serializable
data class LLMErrorMessage(
    override val message: String
) : AgentMessage {
    override val messageType: MessageType = MessageType.ASSISTANT_ERROR
}

/**
 * Represents a message containing a list of ingredients received from a Language Learning Model (LLM).
 */
@Serializable
data class IngredientsMessage(
    val ingredients: List<String>
) : ServerMessage {
    override val messageType = MessageType.INGREDIENTS
    val message: String = "Received Ingredients list from LLM"
}

@Serializable
data class AddProductToCartMessage(
    val product: Product
) : ServerMessage {
    override val messageType = MessageType.ADD_TO_CART
    val message: String = "Product -> Cart. Product: ${product.name}"
}

@Serializable
data class ServerErrorMessage(
    val message: String
) : ServerMessage {
    override val messageType: MessageType = MessageType.ERROR
}

@Serializable
object FinishMessage : ServerMessage {
    override val messageType: MessageType = MessageType.FINISH
}
